source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TTQRCodeScanner_Example', :exclusive => true do
  pod "TTQRCodeScanner", :path => "../"
end

target 'TTQRCodeScanner_Tests', :exclusive => true do
  pod "TTQRCodeScanner", :path => "../"

  
end
